import type { College, User, DashboardStats } from "./types"

export const mockUsers: { user: User; password: string }[] = [
  {
    user: { id: "1", name: "Admin User", email: "admin@degreefyd.com", role: "admin" },
    password: "admin123",
  },
  {
    user: { id: "2", name: "Student User", email: "student@degreefyd.com", role: "student" },
    password: "student123",
  },
]

export const mockColleges: College[] = [
  {
    id: "1",
    slug: "iit-bombay",
    name: "Indian Institute of Technology Bombay",
    description:
      "IIT Bombay is one of the premier engineering institutions in India, established in 1958. It has consistently been ranked among the top engineering colleges in the country and offers a wide range of undergraduate, postgraduate, and doctoral programs. The campus spans over 550 acres in Powai, Mumbai, and is home to cutting-edge research facilities and a vibrant student community.",
    shortDescription: "Premier engineering institution known for excellence in technology and research.",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&h=100&fit=crop",
    location: "Powai, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    established: 1958,
    type: "Public",
    accreditation: "NAAC A++",
    rating: 4.8,
    ranking: 1,
    status: "published",
    facilities: ["Library", "Hostel", "Sports Complex", "Research Labs", "Cafeteria", "Wi-Fi Campus", "Medical Center", "Auditorium"],
    courses: [
      { id: "c1", name: "B.Tech Computer Science", duration: "4 Years", fees: 250000, seats: 120, description: "Comprehensive CS program", eligibility: "JEE Advanced" },
      { id: "c2", name: "B.Tech Electrical Engineering", duration: "4 Years", fees: 250000, seats: 100, description: "Core electrical engineering program", eligibility: "JEE Advanced" },
      { id: "c3", name: "M.Tech Data Science", duration: "2 Years", fees: 200000, seats: 60, description: "Advanced data science program", eligibility: "GATE" },
      { id: "c4", name: "MBA", duration: "2 Years", fees: 800000, seats: 40, description: "Management program by SJMSOM", eligibility: "CAT" },
    ],
    feeStructure: [
      { courseId: "c1", courseName: "B.Tech Computer Science", tuition: 200000, hostel: 30000, other: 20000, total: 250000 },
      { courseId: "c2", courseName: "B.Tech Electrical Engineering", tuition: 200000, hostel: 30000, other: 20000, total: 250000 },
      { courseId: "c3", courseName: "M.Tech Data Science", tuition: 160000, hostel: 25000, other: 15000, total: 200000 },
      { courseId: "c4", courseName: "MBA", tuition: 700000, hostel: 60000, other: 40000, total: 800000 },
    ],
    placement: {
      percentage: 95,
      averagePackage: 2100000,
      highestPackage: 25000000,
      topRecruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs", "Apple", "Meta"],
      yearWiseData: [
        { year: "2022", percentage: 93, avgPackage: 1800000 },
        { year: "2023", percentage: 94, avgPackage: 1950000 },
        { year: "2024", percentage: 95, avgPackage: 2100000 },
      ],
    },
    eligibility: [
      { courseId: "c1", courseName: "B.Tech Computer Science", entranceExams: ["JEE Advanced"], criteria: "Minimum 75% in 10+2 with PCM" },
      { courseId: "c2", courseName: "B.Tech Electrical Engineering", entranceExams: ["JEE Advanced"], criteria: "Minimum 75% in 10+2 with PCM" },
      { courseId: "c3", courseName: "M.Tech Data Science", entranceExams: ["GATE"], criteria: "B.Tech/BE with valid GATE score" },
      { courseId: "c4", courseName: "MBA", entranceExams: ["CAT"], criteria: "Graduation with valid CAT score" },
    ],
    createdAt: "2024-01-15",
    updatedAt: "2024-06-20",
  },
  {
    id: "2",
    slug: "iit-delhi",
    name: "Indian Institute of Technology Delhi",
    description:
      "IIT Delhi is one of the most prestigious engineering institutions in India, located in New Delhi. Established in 1961, it offers a wide array of programs in engineering, sciences, management, and humanities. The institute is renowned for its research output and has produced numerous notable alumni.",
    shortDescription: "Leading technology institute in the national capital with world-class research.",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&h=100&fit=crop",
    location: "Hauz Khas, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    established: 1961,
    type: "Public",
    accreditation: "NAAC A++",
    rating: 4.7,
    ranking: 2,
    status: "published",
    facilities: ["Library", "Hostel", "Sports Complex", "Research Labs", "Cafeteria", "Wi-Fi Campus", "Incubation Center"],
    courses: [
      { id: "c5", name: "B.Tech Computer Science", duration: "4 Years", fees: 240000, seats: 110, description: "Flagship CS program", eligibility: "JEE Advanced" },
      { id: "c6", name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 240000, seats: 90, description: "Core mechanical engineering", eligibility: "JEE Advanced" },
      { id: "c7", name: "M.Tech AI & ML", duration: "2 Years", fees: 190000, seats: 50, description: "AI and Machine Learning specialization", eligibility: "GATE" },
    ],
    feeStructure: [
      { courseId: "c5", courseName: "B.Tech Computer Science", tuition: 190000, hostel: 30000, other: 20000, total: 240000 },
      { courseId: "c6", courseName: "B.Tech Mechanical Engineering", tuition: 190000, hostel: 30000, other: 20000, total: 240000 },
      { courseId: "c7", courseName: "M.Tech AI & ML", tuition: 150000, hostel: 25000, other: 15000, total: 190000 },
    ],
    placement: {
      percentage: 93,
      averagePackage: 1950000,
      highestPackage: 22000000,
      topRecruiters: ["Google", "Microsoft", "Adobe", "Samsung", "Uber"],
      yearWiseData: [
        { year: "2022", percentage: 91, avgPackage: 1700000 },
        { year: "2023", percentage: 92, avgPackage: 1800000 },
        { year: "2024", percentage: 93, avgPackage: 1950000 },
      ],
    },
    eligibility: [
      { courseId: "c5", courseName: "B.Tech Computer Science", entranceExams: ["JEE Advanced"], criteria: "Minimum 75% in 10+2 with PCM" },
      { courseId: "c6", courseName: "B.Tech Mechanical Engineering", entranceExams: ["JEE Advanced"], criteria: "Minimum 75% in 10+2 with PCM" },
      { courseId: "c7", courseName: "M.Tech AI & ML", entranceExams: ["GATE"], criteria: "B.Tech/BE with valid GATE score" },
    ],
    createdAt: "2024-01-20",
    updatedAt: "2024-06-18",
  },
  {
    id: "3",
    slug: "bits-pilani",
    name: "Birla Institute of Technology and Science, Pilani",
    description:
      "BITS Pilani is a prestigious private engineering institution that has been at the forefront of education since 1964. Known for its unique practice school program and flexible academic structure, it offers students a holistic education experience across multiple campuses in India and Dubai.",
    shortDescription: "Prestigious private institution known for flexible academics and industry connections.",
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&h=100&fit=crop",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    established: 1964,
    type: "Private",
    accreditation: "NAAC A",
    rating: 4.5,
    ranking: 5,
    status: "published",
    facilities: ["Library", "Hostel", "Sports Complex", "Research Labs", "Cafeteria", "Wi-Fi Campus", "Gym"],
    courses: [
      { id: "c8", name: "B.E. Computer Science", duration: "4 Years", fees: 500000, seats: 150, description: "Industry-oriented CS program", eligibility: "BITSAT" },
      { id: "c9", name: "B.E. Electronics", duration: "4 Years", fees: 500000, seats: 120, description: "Electronics and communication", eligibility: "BITSAT" },
      { id: "c10", name: "M.Sc. Economics", duration: "2 Years", fees: 350000, seats: 40, description: "Economics with dual degree option", eligibility: "BITSAT" },
    ],
    feeStructure: [
      { courseId: "c8", courseName: "B.E. Computer Science", tuition: 400000, hostel: 60000, other: 40000, total: 500000 },
      { courseId: "c9", courseName: "B.E. Electronics", tuition: 400000, hostel: 60000, other: 40000, total: 500000 },
      { courseId: "c10", courseName: "M.Sc. Economics", tuition: 270000, hostel: 50000, other: 30000, total: 350000 },
    ],
    placement: {
      percentage: 88,
      averagePackage: 1600000,
      highestPackage: 18000000,
      topRecruiters: ["Google", "Microsoft", "Flipkart", "Oracle", "DE Shaw"],
      yearWiseData: [
        { year: "2022", percentage: 85, avgPackage: 1400000 },
        { year: "2023", percentage: 87, avgPackage: 1500000 },
        { year: "2024", percentage: 88, avgPackage: 1600000 },
      ],
    },
    eligibility: [
      { courseId: "c8", courseName: "B.E. Computer Science", entranceExams: ["BITSAT"], criteria: "Minimum 75% in 10+2 with PCM" },
      { courseId: "c9", courseName: "B.E. Electronics", entranceExams: ["BITSAT"], criteria: "Minimum 75% in 10+2 with PCM" },
      { courseId: "c10", courseName: "M.Sc. Economics", entranceExams: ["BITSAT"], criteria: "Minimum 75% in 10+2" },
    ],
    createdAt: "2024-02-01",
    updatedAt: "2024-05-15",
  },
  {
    id: "4",
    slug: "nit-trichy",
    name: "National Institute of Technology Tiruchirappalli",
    description:
      "NIT Trichy is one of the premier NITs in India, established in 1964. It is recognized for its academic excellence, strong alumni network, and excellent placement record. The campus is spread over 800 acres with state-of-the-art facilities.",
    shortDescription: "Top-ranked NIT with excellent placements and sprawling campus.",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&h=100&fit=crop",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    established: 1964,
    type: "Public",
    accreditation: "NAAC A++",
    rating: 4.4,
    ranking: 8,
    status: "published",
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Cafeteria", "Wi-Fi Campus"],
    courses: [
      { id: "c11", name: "B.Tech Computer Science", duration: "4 Years", fees: 180000, seats: 80, description: "Strong CS fundamentals", eligibility: "JEE Main" },
      { id: "c12", name: "B.Tech Civil Engineering", duration: "4 Years", fees: 180000, seats: 70, description: "Civil engineering fundamentals", eligibility: "JEE Main" },
    ],
    feeStructure: [
      { courseId: "c11", courseName: "B.Tech Computer Science", tuition: 140000, hostel: 25000, other: 15000, total: 180000 },
      { courseId: "c12", courseName: "B.Tech Civil Engineering", tuition: 140000, hostel: 25000, other: 15000, total: 180000 },
    ],
    placement: {
      percentage: 90,
      averagePackage: 1200000,
      highestPackage: 15000000,
      topRecruiters: ["TCS", "Infosys", "Microsoft", "Amazon", "Wipro"],
      yearWiseData: [
        { year: "2022", percentage: 88, avgPackage: 1000000 },
        { year: "2023", percentage: 89, avgPackage: 1100000 },
        { year: "2024", percentage: 90, avgPackage: 1200000 },
      ],
    },
    eligibility: [
      { courseId: "c11", courseName: "B.Tech Computer Science", entranceExams: ["JEE Main"], criteria: "Minimum 75% in 10+2 with PCM" },
      { courseId: "c12", courseName: "B.Tech Civil Engineering", entranceExams: ["JEE Main"], criteria: "Minimum 75% in 10+2 with PCM" },
    ],
    createdAt: "2024-02-10",
    updatedAt: "2024-05-22",
  },
  {
    id: "5",
    slug: "iim-ahmedabad",
    name: "Indian Institute of Management Ahmedabad",
    description:
      "IIM Ahmedabad is the premier business school in India, established in 1961. It is consistently ranked as the top management institute in the country and is known for its rigorous academic programs, case-study pedagogy, and exceptional placement record.",
    shortDescription: "India's top business school with world-class MBA programs.",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&h=100&fit=crop",
    location: "Vastrapur, Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    established: 1961,
    type: "Public",
    accreditation: "AACSB, EQUIS",
    rating: 4.9,
    ranking: 1,
    status: "published",
    facilities: ["Library", "Hostel", "Auditorium", "Sports Complex", "Cafeteria", "Wi-Fi Campus", "Conference Halls"],
    courses: [
      { id: "c13", name: "PGP (MBA)", duration: "2 Years", fees: 2800000, seats: 400, description: "Flagship MBA program", eligibility: "CAT" },
      { id: "c14", name: "PGPX (Executive MBA)", duration: "1 Year", fees: 3200000, seats: 80, description: "One-year executive program", eligibility: "GMAT" },
      { id: "c15", name: "PhD in Management", duration: "4 Years", fees: 100000, seats: 30, description: "Doctoral program in management", eligibility: "CAT/GMAT" },
    ],
    feeStructure: [
      { courseId: "c13", courseName: "PGP (MBA)", tuition: 2500000, hostel: 200000, other: 100000, total: 2800000 },
      { courseId: "c14", courseName: "PGPX (Executive MBA)", tuition: 3000000, hostel: 150000, other: 50000, total: 3200000 },
      { courseId: "c15", courseName: "PhD in Management", tuition: 50000, hostel: 30000, other: 20000, total: 100000 },
    ],
    placement: {
      percentage: 100,
      averagePackage: 3500000,
      highestPackage: 75000000,
      topRecruiters: ["McKinsey", "BCG", "Bain", "Goldman Sachs", "JP Morgan", "Amazon"],
      yearWiseData: [
        { year: "2022", percentage: 100, avgPackage: 3200000 },
        { year: "2023", percentage: 100, avgPackage: 3400000 },
        { year: "2024", percentage: 100, avgPackage: 3500000 },
      ],
    },
    eligibility: [
      { courseId: "c13", courseName: "PGP (MBA)", entranceExams: ["CAT"], criteria: "Graduation with valid CAT score" },
      { courseId: "c14", courseName: "PGPX (Executive MBA)", entranceExams: ["GMAT"], criteria: "Graduation + 5 years work experience" },
      { courseId: "c15", courseName: "PhD in Management", entranceExams: ["CAT", "GMAT"], criteria: "PG degree with research aptitude" },
    ],
    createdAt: "2024-01-25",
    updatedAt: "2024-06-10",
  },
  {
    id: "6",
    slug: "vit-vellore",
    name: "Vellore Institute of Technology",
    description:
      "VIT is one of India's top private universities, known for its modern infrastructure and industry-oriented curriculum. Founded in 1984, VIT has grown to become one of the largest private engineering institutions in the country with multiple campuses.",
    shortDescription: "Leading private university with industry-driven curriculum and global partnerships.",
    image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&h=100&fit=crop",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    established: 1984,
    type: "Private",
    accreditation: "NAAC A++",
    rating: 4.2,
    ranking: 12,
    status: "published",
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Cafeteria", "Wi-Fi Campus", "Swimming Pool", "Gym"],
    courses: [
      { id: "c16", name: "B.Tech Computer Science", duration: "4 Years", fees: 350000, seats: 300, description: "Modern CS curriculum", eligibility: "VITEEE" },
      { id: "c17", name: "B.Tech Biotech", duration: "4 Years", fees: 350000, seats: 100, description: "Biotechnology program", eligibility: "VITEEE" },
    ],
    feeStructure: [
      { courseId: "c16", courseName: "B.Tech Computer Science", tuition: 280000, hostel: 45000, other: 25000, total: 350000 },
      { courseId: "c17", courseName: "B.Tech Biotech", tuition: 280000, hostel: 45000, other: 25000, total: 350000 },
    ],
    placement: {
      percentage: 82,
      averagePackage: 900000,
      highestPackage: 12000000,
      topRecruiters: ["TCS", "Infosys", "Cognizant", "Wipro", "Amazon"],
      yearWiseData: [
        { year: "2022", percentage: 79, avgPackage: 750000 },
        { year: "2023", percentage: 81, avgPackage: 850000 },
        { year: "2024", percentage: 82, avgPackage: 900000 },
      ],
    },
    eligibility: [
      { courseId: "c16", courseName: "B.Tech Computer Science", entranceExams: ["VITEEE"], criteria: "Minimum 60% in 10+2 with PCM" },
      { courseId: "c17", courseName: "B.Tech Biotech", entranceExams: ["VITEEE"], criteria: "Minimum 60% in 10+2 with PCB/PCM" },
    ],
    createdAt: "2024-03-01",
    updatedAt: "2024-06-05",
  },
  {
    id: "7",
    slug: "iisc-bangalore",
    name: "Indian Institute of Science, Bangalore",
    description:
      "IISc Bangalore is the premier research institution in India, established in 1909. It is known for its outstanding contributions to science and engineering research. The institute offers primarily postgraduate and doctoral programs.",
    shortDescription: "India's top research institution for science and engineering.",
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&h=100&fit=crop",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    established: 1909,
    type: "Public",
    accreditation: "NAAC A++",
    rating: 4.9,
    ranking: 1,
    status: "published",
    facilities: ["Library", "Research Labs", "Hostel", "Sports Complex", "Cafeteria", "Auditorium", "Museum"],
    courses: [
      { id: "c18", name: "B.S. (Research)", duration: "4 Years", fees: 50000, seats: 120, description: "Undergraduate research program", eligibility: "JEE Main/KVPY" },
      { id: "c19", name: "M.Tech Computer Science", duration: "2 Years", fees: 40000, seats: 40, description: "Advanced CS research", eligibility: "GATE" },
      { id: "c20", name: "PhD in Physics", duration: "5 Years", fees: 30000, seats: 25, description: "Doctoral research in physics", eligibility: "IISc Entrance" },
    ],
    feeStructure: [
      { courseId: "c18", courseName: "B.S. (Research)", tuition: 35000, hostel: 10000, other: 5000, total: 50000 },
      { courseId: "c19", courseName: "M.Tech Computer Science", tuition: 25000, hostel: 10000, other: 5000, total: 40000 },
      { courseId: "c20", courseName: "PhD in Physics", tuition: 20000, hostel: 5000, other: 5000, total: 30000 },
    ],
    placement: {
      percentage: 85,
      averagePackage: 2500000,
      highestPackage: 30000000,
      topRecruiters: ["Google", "Intel", "Qualcomm", "Samsung", "ISRO"],
      yearWiseData: [
        { year: "2022", percentage: 83, avgPackage: 2200000 },
        { year: "2023", percentage: 84, avgPackage: 2350000 },
        { year: "2024", percentage: 85, avgPackage: 2500000 },
      ],
    },
    eligibility: [
      { courseId: "c18", courseName: "B.S. (Research)", entranceExams: ["JEE Main", "KVPY"], criteria: "10+2 with PCM/PCB" },
      { courseId: "c19", courseName: "M.Tech Computer Science", entranceExams: ["GATE"], criteria: "B.Tech/BE with valid GATE score" },
      { courseId: "c20", courseName: "PhD in Physics", entranceExams: ["IISc Entrance"], criteria: "M.Sc. Physics with first class" },
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-06-15",
  },
  {
    id: "8",
    slug: "srm-chennai",
    name: "SRM Institute of Science and Technology",
    description:
      "SRM University is a well-known private institution in Chennai, offering a wide range of programs in engineering, medicine, science, and management. Known for its modern campus and industry tie-ups, SRM attracts students from across India.",
    shortDescription: "Private university with diverse programs and strong industry connections.",
    image: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&h=100&fit=crop",
    location: "Kattankulathur, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    established: 1985,
    type: "Deemed",
    accreditation: "NAAC A++",
    rating: 4.0,
    ranking: 18,
    status: "published",
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "Cafeteria", "Hospital", "Gym"],
    courses: [
      { id: "c21", name: "B.Tech Computer Science", duration: "4 Years", fees: 400000, seats: 500, description: "Large-scale CS program", eligibility: "SRMJEE" },
      { id: "c22", name: "B.Tech Mechanical Engineering", duration: "4 Years", fees: 380000, seats: 200, description: "Mechanical engineering", eligibility: "SRMJEE" },
    ],
    feeStructure: [
      { courseId: "c21", courseName: "B.Tech Computer Science", tuition: 320000, hostel: 50000, other: 30000, total: 400000 },
      { courseId: "c22", courseName: "B.Tech Mechanical Engineering", tuition: 300000, hostel: 50000, other: 30000, total: 380000 },
    ],
    placement: {
      percentage: 78,
      averagePackage: 700000,
      highestPackage: 10000000,
      topRecruiters: ["TCS", "Infosys", "HCL", "Cognizant", "Accenture"],
      yearWiseData: [
        { year: "2022", percentage: 75, avgPackage: 600000 },
        { year: "2023", percentage: 77, avgPackage: 650000 },
        { year: "2024", percentage: 78, avgPackage: 700000 },
      ],
    },
    eligibility: [
      { courseId: "c21", courseName: "B.Tech Computer Science", entranceExams: ["SRMJEE"], criteria: "Minimum 50% in 10+2 with PCM" },
      { courseId: "c22", courseName: "B.Tech Mechanical Engineering", entranceExams: ["SRMJEE"], criteria: "Minimum 50% in 10+2 with PCM" },
    ],
    createdAt: "2024-03-15",
    updatedAt: "2024-05-30",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalColleges: mockColleges.length,
  published: mockColleges.filter((c) => c.status === "published").length,
  drafts: mockColleges.filter((c) => c.status === "draft").length,
  totalCourses: mockColleges.reduce((sum, c) => sum + c.courses.length, 0),
}
